
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fahim MuntasirAkib
 */
public class BazaarPage extends javax.swing.JFrame {

    /**
     * Creates new form BazaarPage
     */
    public BazaarPage() {
        initComponents();
        showBazaarTable();
    }

    private void showBazaarTable(){
        String columnNames[]={ "Item","Cost","Bazaar Man","Date"};
        DefaultTableModel memberModel= new DefaultTableModel(columnNames,0);
        String query= "select *from bazaar_list";
        try{
            //String query;
        ResultSet rs = DBUTILS.queryExecute(query);
        while(rs.next()){
            String Item=rs.getString("item");
            String Cost=rs.getString("cost");
            String Bazaar_Man=rs.getString("bazaar_man");
            String Date=rs.getString("date");

            String data[]={Item,Cost,Bazaar_Man,Date};
            memberModel.addRow(data);

        }
        bazaar_table.setModel(memberModel);
        }catch(Exception e){}
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bazaar_date = new com.toedter.calendar.JDateChooser();
        item_name = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        bazaar_man = new javax.swing.JTextField();
        bazaar_add_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bazaar_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 111, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bazaar_date.setBackground(new java.awt.Color(25, 111, 61));
        jPanel1.add(bazaar_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 170, -1));

        item_name.setBackground(new java.awt.Color(25, 111, 61));
        item_name.setFont(new java.awt.Font("Kalpurush", 1, 14)); // NOI18N
        item_name.setForeground(new java.awt.Color(255, 255, 255));
        item_name.setBorder(null);
        jPanel1.add(item_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 170, -1));

        cost.setBackground(new java.awt.Color(25, 111, 61));
        cost.setFont(new java.awt.Font("Kalpurush", 1, 14)); // NOI18N
        cost.setForeground(new java.awt.Color(255, 255, 255));
        cost.setBorder(null);
        jPanel1.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 170, -1));

        bazaar_man.setBackground(new java.awt.Color(25, 111, 61));
        bazaar_man.setFont(new java.awt.Font("Kalpurush", 1, 14)); // NOI18N
        bazaar_man.setForeground(new java.awt.Color(255, 255, 255));
        bazaar_man.setBorder(null);
        jPanel1.add(bazaar_man, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 170, -1));

        bazaar_add_button.setBackground(new java.awt.Color(0, 102, 0));
        bazaar_add_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bazaar_add_button.setForeground(new java.awt.Color(255, 255, 255));
        bazaar_add_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-add-34.png")); // NOI18N
        bazaar_add_button.setText("ADD");
        bazaar_add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bazaar_add_button.setContentAreaFilled(false);
        bazaar_add_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bazaar_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaar_add_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(bazaar_add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 180, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date of Bazaar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 80, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cost");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 52, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bazaar Man");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 100, -1));

        bazaar_table.setBackground(new java.awt.Color(25, 111, 61));
        bazaar_table.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        bazaar_table.setForeground(new java.awt.Color(255, 255, 255));
        bazaar_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bazaar_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bazaar_table.setRowHeight(30);
        bazaar_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bazaar_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bazaar_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 440, 320));

        jButton1.setBackground(new java.awt.Color(25, 111, 61));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-dashboard-43letest.png")); // NOI18N
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 460, -1, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("____________________________________");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("____________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("____________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, 20));

        jPanel2.setBackground(new java.awt.Color(254, 2, 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 40, 50));

        jPanel3.setBackground(new java.awt.Color(46, 204, 113));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 40, 40));

        jPanel4.setBackground(new java.awt.Color(46, 204, 113));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 40, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Jokerman", 0, 36)); // NOI18N
        jLabel9.setText("BAZAAR LIST");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\list404.png")); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jPanel6.setBackground(new java.awt.Color(254, 2, 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 40, 50));

        jPanel7.setBackground(new java.awt.Color(46, 204, 113));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 40, 40));

        jPanel8.setBackground(new java.awt.Color(254, 2, 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 40, 40));

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("■List your day to day Bazaar...");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bazaar_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaar_add_buttonActionPerformed
        // TODO add your handling code here:
        
        
        String date_bazaar = ((JTextField)bazaar_date.getDateEditor().getUiComponent()).getText(); //String.valueOf(bazaar_date.getText());
        String item = item_name.getText();
        String cost_bazaar = cost.getText();
        String man=bazaar_man.getText();
        
     if(date_bazaar.length()!=0 && item.length()!=0 && cost_bazaar.length()!=0){
            String query="insert into bazaar_list (item,cost,bazaar_man,date) values ('"+item+"','"+cost_bazaar+"','"+man+"','"+date_bazaar+"')";
           
         try{
              JOptionPane.showMessageDialog(this,"Bazaar Add Successful.");
             int rs=DBUTILS.queryUpdate(query);
             showBazaarTable();
         }catch(Exception e){
         }
        }
        else{
             JOptionPane.showMessageDialog(this,"Bazaar Add failed!\nPlease fill the form. ");
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_bazaar_add_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

             this.setVisible(false);
             new DashBoard().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bazaar_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bazaar_tableMouseClicked
//        TableColumnModel modelecolonene=bazaar_table.getColumnModel();
//        TableModel modele=bazaar_table.getModel();
//        int total=modelecolonene.getColumnCount();
//        for(int i=0;i<total;i++) {
//            int taille=0;
//            int total2=modele.getRowCount();
//            for(int j=0;i<total2;j++) {
//                if(modele.getValueAt(j,i)!=null) {
//                int taille2=modele.getValueAt(j,i).toString().length()*7;
//                if(taille2>taille) {
//                    taille=taille2;
//                }
//                
//                }modelecolonene.getColumn(i).setPreferredWidth(taille);
//                }
//        }
    }//GEN-LAST:event_bazaar_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BazaarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BazaarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BazaarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BazaarPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BazaarPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bazaar_add_button;
    private com.toedter.calendar.JDateChooser bazaar_date;
    private javax.swing.JTextField bazaar_man;
    private javax.swing.JTable bazaar_table;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField item_name;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
