/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fahim MuntasirAkib
 */
public class DashBoard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bazaar_button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        member_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        give_money_button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        schedule_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        meal_entry_button = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        Back_To_homepage = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jlevel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 111, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-bazaar-100.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 27, -1, -1));

        bazaar_button.setBackground(new java.awt.Color(153, 0, 51));
        bazaar_button.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        bazaar_button.setForeground(new java.awt.Color(255, 255, 255));
        bazaar_button.setText("Bazaar");
        bazaar_button.setBorder(null);
        bazaar_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bazaar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bazaar_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(bazaar_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 220));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-management-100.png")); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 14, -1, 114));

        member_button.setBackground(new java.awt.Color(153, 0, 51));
        member_button.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        member_button.setForeground(new java.awt.Color(255, 255, 255));
        member_button.setText("Members");
        member_button.setBorder(null);
        member_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        member_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_buttonActionPerformed(evt);
            }
        });
        jPanel3.add(member_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, 220));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-give-money-100.png")); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 25, -1, 111));

        give_money_button.setBackground(new java.awt.Color(153, 0, 51));
        give_money_button.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        give_money_button.setForeground(new java.awt.Color(255, 255, 255));
        give_money_button.setText("Give Money");
        give_money_button.setBorder(null);
        give_money_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        give_money_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                give_money_buttonActionPerformed(evt);
            }
        });
        jPanel4.add(give_money_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 130, 220));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-schedule-100.png")); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 32, 98, -1));

        schedule_button.setBackground(new java.awt.Color(153, 0, 51));
        schedule_button.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        schedule_button.setForeground(new java.awt.Color(255, 255, 255));
        schedule_button.setText("Schedule");
        schedule_button.setBorder(null);
        schedule_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        schedule_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schedule_buttonActionPerformed(evt);
            }
        });
        jPanel5.add(schedule_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 130, 220));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-meal-100.png")); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 118, -1));

        meal_entry_button.setBackground(new java.awt.Color(153, 0, 51));
        meal_entry_button.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        meal_entry_button.setForeground(new java.awt.Color(255, 255, 255));
        meal_entry_button.setText("Meal Entry");
        meal_entry_button.setBorder(null);
        meal_entry_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        meal_entry_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meal_entry_buttonActionPerformed(evt);
            }
        });
        jPanel6.add(meal_entry_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 130, 220));

        jPanel7.setBackground(new java.awt.Color(25, 111, 61));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back_To_homepage.setBackground(new java.awt.Color(149, 16, 16));
        Back_To_homepage.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        Back_To_homepage.setForeground(new java.awt.Color(255, 255, 255));
        Back_To_homepage.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-homepage-38.png")); // NOI18N
        Back_To_homepage.setText("HOMEPAGE");
        Back_To_homepage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        Back_To_homepage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back_To_homepage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_To_homepageActionPerformed(evt);
            }
        });
        jPanel7.add(Back_To_homepage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 150, 60));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 900, 100));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 120, 200));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 120, 200));

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 120, 200));

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 120, 200));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel6.setText("DASHBOARD");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 35, -1, 60));

        jlevel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-dashboard-43letest.png")); // NOI18N
        jPanel8.add(jlevel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 900, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void member_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_buttonActionPerformed
        this.setVisible(false);
        new MemberPage().setVisible(true);
    }//GEN-LAST:event_member_buttonActionPerformed

    private void Back_To_homepageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_To_homepageActionPerformed
       this.setVisible(false);
       new HomePage().setVisible(true);
    }//GEN-LAST:event_Back_To_homepageActionPerformed

    private void bazaar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bazaar_buttonActionPerformed
        this.setVisible(false);
        new BazaarPage().setVisible(true);
    }//GEN-LAST:event_bazaar_buttonActionPerformed

    private void meal_entry_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meal_entry_buttonActionPerformed
        this.setVisible(false);
        new Meal_Entry_Page().setVisible(true);
    }//GEN-LAST:event_meal_entry_buttonActionPerformed

    private void schedule_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schedule_buttonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new SchedulePage().setVisible(true);
    }//GEN-LAST:event_schedule_buttonActionPerformed

    private void give_money_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_give_money_buttonActionPerformed
        this.setVisible(false);
        new MoneyGivingPage().setVisible(true);
    }//GEN-LAST:event_give_money_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_To_homepage;
    private javax.swing.JButton bazaar_button;
    private javax.swing.JButton give_money_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jlevel7;
    private javax.swing.JButton meal_entry_button;
    private javax.swing.JButton member_button;
    private javax.swing.JButton schedule_button;
    // End of variables declaration//GEN-END:variables
}
