
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fahim MuntasirAkib
 */
public class MoneyGivingPage extends javax.swing.JFrame {

    /**
     * Creates new form MoneyGivingPage
     */
    public MoneyGivingPage() {
        initComponents();
        showMoneyTable();
    }

    
    
    
   private void showMoneyTable(){
        String columnNames[]={ "Name","Amount","Date"};
        DefaultTableModel memberModel= new DefaultTableModel(columnNames,0);
        String query= "select *from money_manager";
        try{
            //String query;
        ResultSet rs = DBUTILS.queryExecute(query);
        while(rs.next()){
            String Name=rs.getString("name");
            String Amount=rs.getString("amount");
            String Date2=rs.getString("date");
            String data[]={Name,Amount,Date2};
            memberModel.addRow(data);

        }
        show_money_table.setModel(memberModel);
        }catch(Exception e){}
    } 
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name_take_mg = new javax.swing.JTextField();
        money_take = new javax.swing.JTextField();
        date_take_mg = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_money_table = new javax.swing.JTable();
        done_button = new javax.swing.JButton();
        delete_history = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        back_dashboard = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(25, 111, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel1.setText("Mess Reserves");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-money-100.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, -10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 80));

        name_take_mg.setBackground(new java.awt.Color(25, 111, 61));
        name_take_mg.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        name_take_mg.setForeground(new java.awt.Color(255, 255, 255));
        name_take_mg.setBorder(null);
        jPanel1.add(name_take_mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 170, -1));

        money_take.setBackground(new java.awt.Color(25, 111, 61));
        money_take.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        money_take.setForeground(new java.awt.Color(255, 255, 255));
        money_take.setBorder(null);
        jPanel1.add(money_take, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 170, -1));

        date_take_mg.setBackground(new java.awt.Color(25, 111, 61));
        jPanel1.add(date_take_mg, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 242, 170, 30));

        show_money_table.setBackground(new java.awt.Color(25, 111, 61));
        show_money_table.setFont(new java.awt.Font("Maiandra GD", 1, 18)); // NOI18N
        show_money_table.setForeground(new java.awt.Color(255, 255, 255));
        show_money_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        show_money_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        show_money_table.setRowHeight(30);
        jScrollPane1.setViewportView(show_money_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 390, 350));

        done_button.setBackground(new java.awt.Color(0, 102, 0));
        done_button.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        done_button.setForeground(new java.awt.Color(255, 255, 255));
        done_button.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-add-34.png")); // NOI18N
        done_button.setText("ADD");
        done_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        done_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        done_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                done_buttonMouseClicked(evt);
            }
        });
        done_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                done_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(done_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 90, 40));

        delete_history.setBackground(new java.awt.Color(124, 8, 42));
        delete_history.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        delete_history.setForeground(new java.awt.Color(255, 255, 255));
        delete_history.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-delete-34.png")); // NOI18N
        delete_history.setText("DELETE");
        delete_history.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        delete_history.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_historyActionPerformed(evt);
            }
        });
        jPanel1.add(delete_history, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 100, 40));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("____________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 120, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("____________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("____________________________________");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, -1, -1));

        back_dashboard.setBackground(new java.awt.Color(25, 111, 61));
        back_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        back_dashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-dashboard-43letest.png")); // NOI18N
        back_dashboard.setBorder(null);
        back_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_dashboardActionPerformed(evt);
            }
        });
        jPanel1.add(back_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 50, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("____________________________________");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("____________________________________");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 120, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("____________________________________");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("____________________________________");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 120, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("____________________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void done_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_done_buttonActionPerformed
         
        String name_mg = name_take_mg.getText();
        String amount_mg = money_take.getText();
        String date_mg = ((JTextField)date_take_mg.getDateEditor().getUiComponent()).getText(); 
        
        
     if(name_mg.length()!=0 && amount_mg.length()!=0 && date_mg.length()!=0){
            String query="insert into money_manager(name,amount,date) values ('"+name_mg+"','"+amount_mg+"','"+date_mg+"')";
           
         try{
              JOptionPane.showMessageDialog(this,"Money Take Successful.");
             int rs=DBUTILS.queryUpdate(query);
         }catch(Exception e){
         }
        }
        else{
             JOptionPane.showMessageDialog(this,"Money take failed!\nPlease fill the form. ");
        }
     
     showMoneyTable();
        
    }//GEN-LAST:event_done_buttonActionPerformed

    private void delete_historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_historyActionPerformed
        String name_mg2 = name_take_mg.getText();
        
        if(name_mg2.length()!=0){
        String query="delete from money_manager where name= '"+name_mg2+"'";
        try{
              JOptionPane.showMessageDialog(this,"Deleted info Successful.");
             int rs=DBUTILS.queryUpdate(query);
         }catch(Exception e){
         }
        }
        else{
            JOptionPane.showMessageDialog(this,"Deleted failed.\nPlease enter email.");
        }
          showMoneyTable();
    }//GEN-LAST:event_delete_historyActionPerformed

    private void back_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_dashboardActionPerformed
         this.setVisible(false);
        new DashBoard().setVisible(true);
    }//GEN-LAST:event_back_dashboardActionPerformed

    private void done_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_done_buttonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_done_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyGivingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyGivingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyGivingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyGivingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyGivingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_dashboard;
    private com.toedter.calendar.JDateChooser date_take_mg;
    private javax.swing.JButton delete_history;
    private javax.swing.JButton done_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField money_take;
    private javax.swing.JTextField name_take_mg;
    private javax.swing.JTable show_money_table;
    // End of variables declaration//GEN-END:variables
}
