
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Fahim MuntasirAkib
 */
public class SchedulePage extends javax.swing.JFrame {

    /**
     * Creates new form SchedulePage
     */
    public SchedulePage() {
        initComponents();
        showScheduleTable();
    }

    
    
    
     private void showScheduleTable(){
        String columnNames[]={ "DAY","BREAKFAST","LUNCH","DINNER"};
        DefaultTableModel memberModel= new DefaultTableModel(columnNames,0);
        String query= "select *from schedule_table";
        try{
            //String query;
        ResultSet rs = DBUTILS.queryExecute(query);
        while(rs.next()){
            String day=rs.getString("DAY");
            String breakfast=rs.getString("BREAKFAST");
            String lunch=rs.getString("LUNCH");
            String dinner=rs.getString("DINNER");

            String data[]={day,breakfast,lunch,dinner};
            memberModel.addRow(data);

        }
        schedule_table.setModel(memberModel);
        }catch(Exception e){}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        schedule_table = new javax.swing.JTable();
        day_select = new javax.swing.JComboBox<>();
        meal_time = new javax.swing.JComboBox<>();
        change_meal = new javax.swing.JTextField();
        confirm_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        schedule_table.setBackground(new java.awt.Color(0, 51, 51));
        schedule_table.setFont(new java.awt.Font("Kalpurush", 1, 18)); // NOI18N
        schedule_table.setForeground(new java.awt.Color(255, 255, 255));
        schedule_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        schedule_table.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        schedule_table.setRowHeight(38);
        jScrollPane1.setViewportView(schedule_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 430, 300));

        day_select.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        day_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday" }));
        day_select.setBorder(null);
        day_select.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(day_select, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 160, 30));

        meal_time.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        meal_time.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Breakfast", "Lunch", "Dinner" }));
        meal_time.setBorder(null);
        meal_time.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(meal_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 326, 160, 30));

        change_meal.setBackground(new java.awt.Color(0, 51, 51));
        change_meal.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        change_meal.setForeground(new java.awt.Color(255, 255, 255));
        change_meal.setBorder(null);
        jPanel1.add(change_meal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 160, 20));

        confirm_button.setBackground(new java.awt.Color(153, 0, 0));
        confirm_button.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        confirm_button.setForeground(new java.awt.Color(255, 255, 255));
        confirm_button.setText("UPDATE");
        confirm_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        confirm_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        confirm_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(confirm_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 80, 30));

        search_button.setBackground(new java.awt.Color(0, 0, 0));
        search_button.setFont(new java.awt.Font("Maiandra GD", 1, 14)); // NOI18N
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("SEARCH");
        search_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        search_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 80, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Jokerman", 1, 36)); // NOI18N
        jLabel1.setText("MESS MENU");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-restaurant-menu-50.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("||||||||||||||||||||");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 130, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("||||||||||||");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("||||||||||||||||||||");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(768, 20, 130, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("||||||||||||||||||||");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DAY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIME");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("INFO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("___________________________________________________________________________________________________________________________________________________________________________________________");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 20));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("_________________________________");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 386, -1, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("||||||||||||||||||||");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-menu-100.png")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Menu");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel16.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Update Menu");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("||");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("||");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("||");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, -1, -1));

        jButton2.setBackground(new java.awt.Color(25, 111, 61));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Fahim MuntasirAkib\\OneDrive\\Documents\\NetBeansProjects\\Mess Management System\\Image\\icons8-dashboard-43letest.png")); // NOI18N
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirm_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_buttonActionPerformed
        String day_st_up=day_select.getSelectedItem().toString();
        String meal_time_st_up=meal_time.getSelectedItem().toString();
        String meal_change_st=change_meal.getText(); 
        
        
        if(meal_time_st_up=="Breakfast"){
        String query="UPDATE schedule_table SET BREAKFAST='"+meal_change_st+"'WHERE DAY='"+day_st_up+"'";
            try{
            int rs=DBUTILS.queryUpdate(query);
            JOptionPane.showMessageDialog(this,"Update Successful.");
        }catch(Exception e){
            e.printStackTrace();
        }        
        showScheduleTable();
        }
        
         if(meal_time_st_up=="Lunch"){
        String query="UPDATE schedule_table SET LUNCH='"+meal_change_st+"'WHERE DAY='"+day_st_up+"'";
            try{
            int rs = DBUTILS.queryUpdate(query);
            JOptionPane.showMessageDialog(this,"Update Successful.");
        }catch(Exception e){
          e.printStackTrace();
        }        
        showScheduleTable();
        }
         
        
          if(meal_time_st_up=="Dinner"){
        String query="UPDATE schedule_table SET DINNER='"+meal_change_st+"'where DAY='"+day_st_up+"'";
            try{
            int rs = DBUTILS.queryUpdate(query);
            JOptionPane.showMessageDialog(this,"Update Successful.");
        }catch(Exception e){
          e.printStackTrace();
        }        
        showScheduleTable();
        }
         
    
        
    }//GEN-LAST:event_confirm_buttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        String day_st = day_select.getSelectedItem().toString();
        String meal_time_st = meal_time.getSelectedItem().toString();
        //String meal_change_st = change_meal.getText(); 
        String query="select * from schedule_table where DAY='"+day_st+"'";
       
       if(meal_time_st=="Breakfast"){
            try{
            ResultSet rs = DBUTILS.queryExecute(query);
            if(rs.next()){
                change_meal.setText(rs.getString("BREAKFAST"));
            }
        }catch(Exception e){
           // System.out.println("not connected");
        } 
       }
       else if(meal_time_st=="Lunch"){
            try{
            ResultSet rs = DBUTILS.queryExecute(query);
            if(rs.next()){
                change_meal.setText(rs.getString("LUNCH"));
            }
        }catch(Exception e){
           // System.out.println("not connected");
        } 
       }
       else if(meal_time_st=="Dinner"){
            try{
            ResultSet rs = DBUTILS.queryExecute(query);
            if(rs.next()){
                change_meal.setText(rs.getString("DINNER"));
            }
        }catch(Exception e){
           // System.out.println("not connected");
        } 
       }
       
    }//GEN-LAST:event_search_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.setVisible(false);
        new DashBoard().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField change_meal;
    private javax.swing.JButton confirm_button;
    private javax.swing.JComboBox<String> day_select;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> meal_time;
    private javax.swing.JTable schedule_table;
    private javax.swing.JButton search_button;
    // End of variables declaration//GEN-END:variables
}
